package com.myway;

import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.myway.gui.front.moyentp.AfficherToutMoyentp;

import static com.codename1.ui.CN.getCurrentForm;
import static com.codename1.ui.CN.updateNetworkThreadCount;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;

 
    public static Resources res;

    public void init(Object context) {
        res = UIManager.initFirstTheme("/theme");
        updateNetworkThreadCount(3);
        Toolbar.setGlobalToolbar(true);
        
        // Navigate to AfficheToutmoyentp form
       AfficherToutMoyentp afficheToutMoyentp = new AfficherToutMoyentp(getCurrentForm());
afficheToutMoyentp.show();
    }

 

    public void destroy() {
    }

}
